# do add the config to application-messages.properties
# title
title.production.${screenId?lower_case}.completeForm=${screenName}更新完了
title.production.${screenId?lower_case}.createForm=${screenName}新規登録
title.production.${screenId?lower_case}.list=${screenName}一覧
title.production.${screenId?lower_case}.importForm=${screenName}インポート
title.production.${screenId?lower_case}.updateForm=${screenName}編集
